package common

// Code generated by protoc-gen-go.
// source: nationalwar_msg.proto
// DO NOT EDIT!

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NationalWarErrCode int32

const (
	NationalWarErrCode_Success       NationalWarErrCode = 0
	NationalWarErrCode_Fail          NationalWarErrCode = 1
	NationalWarErrCode_NoOpen        NationalWarErrCode = 2
	NationalWarErrCode_NoGuild       NationalWarErrCode = 3
	NationalWarErrCode_JobLimit      NationalWarErrCode = 4
	NationalWarErrCode_LevelLimit    NationalWarErrCode = 5
	NationalWarErrCode_HasRegistered NationalWarErrCode = 6
	NationalWarErrCode_OutRegisterTm NationalWarErrCode = 7
	NationalWarErrCode_WarNoExist    NationalWarErrCode = 8
	NationalWarErrCode_NoRegistered  NationalWarErrCode = 9
	NationalWarErrCode_OutWarTm      NationalWarErrCode = 10
	NationalWarErrCode_HoldNoExist   NationalWarErrCode = 11
)

var NationalWarErrCode_name = map[int32]string{
	0:  "Success",
	1:  "Fail",
	2:  "NoOpen",
	3:  "NoGuild",
	4:  "JobLimit",
	5:  "LevelLimit",
	6:  "HasRegistered",
	7:  "OutRegisterTm",
	8:  "WarNoExist",
	9:  "NoRegistered",
	10: "OutWarTm",
	11: "HoldNoExist",
}
var NationalWarErrCode_value = map[string]int32{
	"Success":       0,
	"Fail":          1,
	"NoOpen":        2,
	"NoGuild":       3,
	"JobLimit":      4,
	"LevelLimit":    5,
	"HasRegistered": 6,
	"OutRegisterTm": 7,
	"WarNoExist":    8,
	"NoRegistered":  9,
	"OutWarTm":      10,
	"HoldNoExist":   11,
}

func (x NationalWarErrCode) Enum() *NationalWarErrCode {
	p := new(NationalWarErrCode)
	*p = x
	return p
}
func (x NationalWarErrCode) String() string {
	return proto.EnumName(NationalWarErrCode_name, int32(x))
}
func (x *NationalWarErrCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NationalWarErrCode_value, data, "NationalWarErrCode")
	if err != nil {
		return err
	}
	*x = NationalWarErrCode(value)
	return nil
}
func (NationalWarErrCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor60, []int{0} }

type ServerInfo struct {
	ServerID         *string `protobuf:"bytes,1,req,name=ServerID" json:"ServerID,omitempty"`
	ServerName       *string `protobuf:"bytes,2,req,name=ServerName" json:"ServerName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{0} }

func (m *ServerInfo) GetServerID() string {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return ""
}

func (m *ServerInfo) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 登陆同步状态
// 主城入口需要
type NationWar_LoginSyncInfo struct {
	ZoneID          *int32        `protobuf:"varint,1,req,name=ZoneID" json:"ZoneID,omitempty"`
	ZoneNum         *int32        `protobuf:"varint,2,req,name=ZoneNum" json:"ZoneNum,omitempty"`
	RunState        *int32        `protobuf:"varint,3,req,name=RunState" json:"RunState,omitempty"`
	HasRegistered   *bool         `protobuf:"varint,5,req,name=HasRegistered" json:"HasRegistered,omitempty"`
	RegisterStartTm *int64        `protobuf:"varint,6,req,name=RegisterStartTm" json:"RegisterStartTm,omitempty"`
	RegisterEndTm   *int64        `protobuf:"varint,7,req,name=RegisterEndTm" json:"RegisterEndTm,omitempty"`
	WarStartTm      *int64        `protobuf:"varint,8,req,name=WarStartTm" json:"WarStartTm,omitempty"`
	WarEndTm        *int64        `protobuf:"varint,9,req,name=WarEndTm" json:"WarEndTm,omitempty"`
	ServerList      []*ServerInfo `protobuf:"bytes,10,rep,name=ServerList" json:"ServerList,omitempty"`
	// 组织信息登陆时没有下发，这里增加报名需要的组织信息
	GuildObjID       *string `protobuf:"bytes,11,opt,name=GuildObjID" json:"GuildObjID,omitempty"`
	GuildLevel       *int32  `protobuf:"varint,12,opt,name=GuildLevel" json:"GuildLevel,omitempty"`
	GuildJob         *int32  `protobuf:"varint,13,opt,name=GuildJob" json:"GuildJob,omitempty"`
	MineWarNum       *int32  `protobuf:"varint,14,opt,name=MineWarNum" json:"MineWarNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NationWar_LoginSyncInfo) Reset()                    { *m = NationWar_LoginSyncInfo{} }
func (m *NationWar_LoginSyncInfo) String() string            { return proto.CompactTextString(m) }
func (*NationWar_LoginSyncInfo) ProtoMessage()               {}
func (*NationWar_LoginSyncInfo) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{1} }

func (m *NationWar_LoginSyncInfo) GetZoneID() int32 {
	if m != nil && m.ZoneID != nil {
		return *m.ZoneID
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetZoneNum() int32 {
	if m != nil && m.ZoneNum != nil {
		return *m.ZoneNum
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetRunState() int32 {
	if m != nil && m.RunState != nil {
		return *m.RunState
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetHasRegistered() bool {
	if m != nil && m.HasRegistered != nil {
		return *m.HasRegistered
	}
	return false
}

func (m *NationWar_LoginSyncInfo) GetRegisterStartTm() int64 {
	if m != nil && m.RegisterStartTm != nil {
		return *m.RegisterStartTm
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetRegisterEndTm() int64 {
	if m != nil && m.RegisterEndTm != nil {
		return *m.RegisterEndTm
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetWarStartTm() int64 {
	if m != nil && m.WarStartTm != nil {
		return *m.WarStartTm
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetWarEndTm() int64 {
	if m != nil && m.WarEndTm != nil {
		return *m.WarEndTm
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetServerList() []*ServerInfo {
	if m != nil {
		return m.ServerList
	}
	return nil
}

func (m *NationWar_LoginSyncInfo) GetGuildObjID() string {
	if m != nil && m.GuildObjID != nil {
		return *m.GuildObjID
	}
	return ""
}

func (m *NationWar_LoginSyncInfo) GetGuildLevel() int32 {
	if m != nil && m.GuildLevel != nil {
		return *m.GuildLevel
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetGuildJob() int32 {
	if m != nil && m.GuildJob != nil {
		return *m.GuildJob
	}
	return 0
}

func (m *NationWar_LoginSyncInfo) GetMineWarNum() int32 {
	if m != nil && m.MineWarNum != nil {
		return *m.MineWarNum
	}
	return 0
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 请求报名
type NationWar_RegisterRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_RegisterRequest) Reset()                    { *m = NationWar_RegisterRequest{} }
func (m *NationWar_RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*NationWar_RegisterRequest) ProtoMessage()               {}
func (*NationWar_RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{2} }

// 报名回调
type NationWar_RegisterResponse struct {
	Code             *int32 `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	MineWarNum       *int32 `protobuf:"varint,2,req,name=MineWarNum" json:"MineWarNum,omitempty"`
	HasRegistered    *bool  `protobuf:"varint,3,req,name=HasRegistered" json:"HasRegistered,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_RegisterResponse) Reset()                    { *m = NationWar_RegisterResponse{} }
func (m *NationWar_RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*NationWar_RegisterResponse) ProtoMessage()               {}
func (*NationWar_RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{3} }

func (m *NationWar_RegisterResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_RegisterResponse) GetMineWarNum() int32 {
	if m != nil && m.MineWarNum != nil {
		return *m.MineWarNum
	}
	return 0
}

func (m *NationWar_RegisterResponse) GetHasRegistered() bool {
	if m != nil && m.HasRegistered != nil {
		return *m.HasRegistered
	}
	return false
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 打开报名界面需要
// 势力排行榜请求
type NationWar_RegisterRankOpenRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_RegisterRankOpenRequest) Reset()         { *m = NationWar_RegisterRankOpenRequest{} }
func (m *NationWar_RegisterRankOpenRequest) String() string { return proto.CompactTextString(m) }
func (*NationWar_RegisterRankOpenRequest) ProtoMessage()    {}
func (*NationWar_RegisterRankOpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{4}
}

// 势力榜霸主信息
type NationWarRegisterGuild struct {
	ServerID         *string `protobuf:"bytes,1,req,name=ServerID" json:"ServerID,omitempty"`
	GuildObjID       *string `protobuf:"bytes,2,req,name=GuildObjID" json:"GuildObjID,omitempty"`
	GuildName        *string `protobuf:"bytes,3,req,name=GuildName" json:"GuildName,omitempty"`
	GuildPoint       *int32  `protobuf:"varint,4,req,name=GuildPoint" json:"GuildPoint,omitempty"`
	GuildPower       *int32  `protobuf:"varint,5,req,name=GuildPower" json:"GuildPower,omitempty"`
	GuildFrame       *int32  `protobuf:"varint,6,req,name=GuildFrame" json:"GuildFrame,omitempty"`
	GuildIcon        *int32  `protobuf:"varint,7,req,name=GuildIcon" json:"GuildIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NationWarRegisterGuild) Reset()                    { *m = NationWarRegisterGuild{} }
func (m *NationWarRegisterGuild) String() string            { return proto.CompactTextString(m) }
func (*NationWarRegisterGuild) ProtoMessage()               {}
func (*NationWarRegisterGuild) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{5} }

func (m *NationWarRegisterGuild) GetServerID() string {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return ""
}

func (m *NationWarRegisterGuild) GetGuildObjID() string {
	if m != nil && m.GuildObjID != nil {
		return *m.GuildObjID
	}
	return ""
}

func (m *NationWarRegisterGuild) GetGuildName() string {
	if m != nil && m.GuildName != nil {
		return *m.GuildName
	}
	return ""
}

func (m *NationWarRegisterGuild) GetGuildPoint() int32 {
	if m != nil && m.GuildPoint != nil {
		return *m.GuildPoint
	}
	return 0
}

func (m *NationWarRegisterGuild) GetGuildPower() int32 {
	if m != nil && m.GuildPower != nil {
		return *m.GuildPower
	}
	return 0
}

func (m *NationWarRegisterGuild) GetGuildFrame() int32 {
	if m != nil && m.GuildFrame != nil {
		return *m.GuildFrame
	}
	return 0
}

func (m *NationWarRegisterGuild) GetGuildIcon() int32 {
	if m != nil && m.GuildIcon != nil {
		return *m.GuildIcon
	}
	return 0
}

// 势力排行榜回调
// 进入势力榜界面需要的信息
type NationWar_RegisterRankOpenResponse struct {
	Code             *int32                    `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	MineWarNum       *int32                    `protobuf:"varint,2,req,name=MineWarNum" json:"MineWarNum,omitempty"`
	GuildInfo        []*NationWarRegisterGuild `protobuf:"bytes,3,rep,name=GuildInfo" json:"GuildInfo,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *NationWar_RegisterRankOpenResponse) Reset()         { *m = NationWar_RegisterRankOpenResponse{} }
func (m *NationWar_RegisterRankOpenResponse) String() string { return proto.CompactTextString(m) }
func (*NationWar_RegisterRankOpenResponse) ProtoMessage()    {}
func (*NationWar_RegisterRankOpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{6}
}

func (m *NationWar_RegisterRankOpenResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_RegisterRankOpenResponse) GetMineWarNum() int32 {
	if m != nil && m.MineWarNum != nil {
		return *m.MineWarNum
	}
	return 0
}

func (m *NationWar_RegisterRankOpenResponse) GetGuildInfo() []*NationWarRegisterGuild {
	if m != nil {
		return m.GuildInfo
	}
	return nil
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 请求进入地图
type NationWar_OpenWarMapRequest struct {
	WarNum           *int32 `protobuf:"varint,1,req,name=WarNum" json:"WarNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_OpenWarMapRequest) Reset()                    { *m = NationWar_OpenWarMapRequest{} }
func (m *NationWar_OpenWarMapRequest) String() string            { return proto.CompactTextString(m) }
func (*NationWar_OpenWarMapRequest) ProtoMessage()               {}
func (*NationWar_OpenWarMapRequest) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{7} }

func (m *NationWar_OpenWarMapRequest) GetWarNum() int32 {
	if m != nil && m.WarNum != nil {
		return *m.WarNum
	}
	return 0
}

// 地图上需要的战场信息
type NationWarMapInfo struct {
	Camp             *int32 `protobuf:"varint,1,req,name=Camp" json:"Camp,omitempty"`
	WarPoint         *int32 `protobuf:"varint,2,req,name=WarPoint" json:"WarPoint,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWarMapInfo) Reset()                    { *m = NationWarMapInfo{} }
func (m *NationWarMapInfo) String() string            { return proto.CompactTextString(m) }
func (*NationWarMapInfo) ProtoMessage()               {}
func (*NationWarMapInfo) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{8} }

func (m *NationWarMapInfo) GetCamp() int32 {
	if m != nil && m.Camp != nil {
		return *m.Camp
	}
	return 0
}

func (m *NationWarMapInfo) GetWarPoint() int32 {
	if m != nil && m.WarPoint != nil {
		return *m.WarPoint
	}
	return 0
}

// 地图据点信息
type NationWarGridInfo struct {
	X                *int32 `protobuf:"varint,1,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,2,req,name=Y" json:"Y,omitempty"`
	Camp             *int32 `protobuf:"varint,3,opt,name=Camp" json:"Camp,omitempty"`
	HP               *int32 `protobuf:"varint,4,opt,name=HP" json:"HP,omitempty"`
	RefreshTm        *int64 `protobuf:"varint,5,opt,name=RefreshTm" json:"RefreshTm,omitempty"`
	IsLock           *bool  `protobuf:"varint,6,opt,name=IsLock" json:"IsLock,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWarGridInfo) Reset()                    { *m = NationWarGridInfo{} }
func (m *NationWarGridInfo) String() string            { return proto.CompactTextString(m) }
func (*NationWarGridInfo) ProtoMessage()               {}
func (*NationWarGridInfo) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{9} }

func (m *NationWarGridInfo) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NationWarGridInfo) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *NationWarGridInfo) GetCamp() int32 {
	if m != nil && m.Camp != nil {
		return *m.Camp
	}
	return 0
}

func (m *NationWarGridInfo) GetHP() int32 {
	if m != nil && m.HP != nil {
		return *m.HP
	}
	return 0
}

func (m *NationWarGridInfo) GetRefreshTm() int64 {
	if m != nil && m.RefreshTm != nil {
		return *m.RefreshTm
	}
	return 0
}

func (m *NationWarGridInfo) GetIsLock() bool {
	if m != nil && m.IsLock != nil {
		return *m.IsLock
	}
	return false
}

// 进入地图回调
type NationWar_OpenWarMapResponse struct {
	Code             *int32               `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	RemainTm         *int64               `protobuf:"varint,2,req,name=RemainTm" json:"RemainTm,omitempty"`
	MineWarInfo      *NationWarMapInfo    `protobuf:"bytes,3,req,name=MineWarInfo" json:"MineWarInfo,omitempty"`
	OtherWarInfo     *NationWarMapInfo    `protobuf:"bytes,4,req,name=OtherWarInfo" json:"OtherWarInfo,omitempty"`
	Grids            []*NationWarGridInfo `protobuf:"bytes,5,rep,name=Grids" json:"Grids,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *NationWar_OpenWarMapResponse) Reset()                    { *m = NationWar_OpenWarMapResponse{} }
func (m *NationWar_OpenWarMapResponse) String() string            { return proto.CompactTextString(m) }
func (*NationWar_OpenWarMapResponse) ProtoMessage()               {}
func (*NationWar_OpenWarMapResponse) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{10} }

func (m *NationWar_OpenWarMapResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_OpenWarMapResponse) GetRemainTm() int64 {
	if m != nil && m.RemainTm != nil {
		return *m.RemainTm
	}
	return 0
}

func (m *NationWar_OpenWarMapResponse) GetMineWarInfo() *NationWarMapInfo {
	if m != nil {
		return m.MineWarInfo
	}
	return nil
}

func (m *NationWar_OpenWarMapResponse) GetOtherWarInfo() *NationWarMapInfo {
	if m != nil {
		return m.OtherWarInfo
	}
	return nil
}

func (m *NationWar_OpenWarMapResponse) GetGrids() []*NationWarGridInfo {
	if m != nil {
		return m.Grids
	}
	return nil
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 请求战场个人信息
// 进入地图后单独请求
type NationWar_PlayerWarInfoRequest struct {
	WarNum           *int32 `protobuf:"varint,1,req,name=WarNum" json:"WarNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_PlayerWarInfoRequest) Reset()         { *m = NationWar_PlayerWarInfoRequest{} }
func (m *NationWar_PlayerWarInfoRequest) String() string { return proto.CompactTextString(m) }
func (*NationWar_PlayerWarInfoRequest) ProtoMessage()    {}
func (*NationWar_PlayerWarInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{11}
}

func (m *NationWar_PlayerWarInfoRequest) GetWarNum() int32 {
	if m != nil && m.WarNum != nil {
		return *m.WarNum
	}
	return 0
}

// 战场个人信息回调
type NationWar_PlayerWarInfoResponse struct {
	Code             *int32 `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=Y" json:"Y,omitempty"`
	ActionPoint      *int32 `protobuf:"varint,4,req,name=ActionPoint" json:"ActionPoint,omitempty"`
	ActionNxtTm      *int64 `protobuf:"varint,5,req,name=ActionNxtTm" json:"ActionNxtTm,omitempty"`
	KillCount        *int32 `protobuf:"varint,6,req,name=KillCount" json:"KillCount,omitempty"`
	KillCombo        *int32 `protobuf:"varint,7,req,name=KillCombo" json:"KillCombo,omitempty"`
	HPPre            *int32 `protobuf:"varint,8,req,name=HPPre" json:"HPPre,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_PlayerWarInfoResponse) Reset()         { *m = NationWar_PlayerWarInfoResponse{} }
func (m *NationWar_PlayerWarInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NationWar_PlayerWarInfoResponse) ProtoMessage()    {}
func (*NationWar_PlayerWarInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{12}
}

func (m *NationWar_PlayerWarInfoResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_PlayerWarInfoResponse) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NationWar_PlayerWarInfoResponse) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *NationWar_PlayerWarInfoResponse) GetActionPoint() int32 {
	if m != nil && m.ActionPoint != nil {
		return *m.ActionPoint
	}
	return 0
}

func (m *NationWar_PlayerWarInfoResponse) GetActionNxtTm() int64 {
	if m != nil && m.ActionNxtTm != nil {
		return *m.ActionNxtTm
	}
	return 0
}

func (m *NationWar_PlayerWarInfoResponse) GetKillCount() int32 {
	if m != nil && m.KillCount != nil {
		return *m.KillCount
	}
	return 0
}

func (m *NationWar_PlayerWarInfoResponse) GetKillCombo() int32 {
	if m != nil && m.KillCombo != nil {
		return *m.KillCombo
	}
	return 0
}

func (m *NationWar_PlayerWarInfoResponse) GetHPPre() int32 {
	if m != nil && m.HPPre != nil {
		return *m.HPPre
	}
	return 0
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 查看据点详情请求
// 打开弹窗需求
type NationWar_StrongholdDetailRequest struct {
	WarNum           *int32 `protobuf:"varint,1,req,name=WarNum" json:"WarNum,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=Y" json:"Y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_StrongholdDetailRequest) Reset()         { *m = NationWar_StrongholdDetailRequest{} }
func (m *NationWar_StrongholdDetailRequest) String() string { return proto.CompactTextString(m) }
func (*NationWar_StrongholdDetailRequest) ProtoMessage()    {}
func (*NationWar_StrongholdDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{13}
}

func (m *NationWar_StrongholdDetailRequest) GetWarNum() int32 {
	if m != nil && m.WarNum != nil {
		return *m.WarNum
	}
	return 0
}

func (m *NationWar_StrongholdDetailRequest) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NationWar_StrongholdDetailRequest) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

// 复活列表信息
type ResurgenceInfo struct {
	ServerID           *string `protobuf:"bytes,1,req,name=ServerID" json:"ServerID,omitempty"`
	GuildObjID         *string `protobuf:"bytes,2,req,name=GuildObjID" json:"GuildObjID,omitempty"`
	GuildName          *string `protobuf:"bytes,3,req,name=GuildName" json:"GuildName,omitempty"`
	PlayerName         *string `protobuf:"bytes,4,req,name=PlayerName" json:"PlayerName,omitempty"`
	PlayerPower        *int32  `protobuf:"varint,5,req,name=PlayerPower" json:"PlayerPower,omitempty"`
	PlayerPoint        *int32  `protobuf:"varint,6,req,name=PlayerPoint" json:"PlayerPoint,omitempty"`
	PlayerResurgenceTm *int64  `protobuf:"varint,7,req,name=PlayerResurgenceTm" json:"PlayerResurgenceTm,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *ResurgenceInfo) Reset()                    { *m = ResurgenceInfo{} }
func (m *ResurgenceInfo) String() string            { return proto.CompactTextString(m) }
func (*ResurgenceInfo) ProtoMessage()               {}
func (*ResurgenceInfo) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{14} }

func (m *ResurgenceInfo) GetServerID() string {
	if m != nil && m.ServerID != nil {
		return *m.ServerID
	}
	return ""
}

func (m *ResurgenceInfo) GetGuildObjID() string {
	if m != nil && m.GuildObjID != nil {
		return *m.GuildObjID
	}
	return ""
}

func (m *ResurgenceInfo) GetGuildName() string {
	if m != nil && m.GuildName != nil {
		return *m.GuildName
	}
	return ""
}

func (m *ResurgenceInfo) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *ResurgenceInfo) GetPlayerPower() int32 {
	if m != nil && m.PlayerPower != nil {
		return *m.PlayerPower
	}
	return 0
}

func (m *ResurgenceInfo) GetPlayerPoint() int32 {
	if m != nil && m.PlayerPoint != nil {
		return *m.PlayerPoint
	}
	return 0
}

func (m *ResurgenceInfo) GetPlayerResurgenceTm() int64 {
	if m != nil && m.PlayerResurgenceTm != nil {
		return *m.PlayerResurgenceTm
	}
	return 0
}

// 营地信息
type CampsiteDetail struct {
	ResurgenceList   []*ResurgenceInfo `protobuf:"bytes,1,rep,name=ResurgenceList" json:"ResurgenceList,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *CampsiteDetail) Reset()                    { *m = CampsiteDetail{} }
func (m *CampsiteDetail) String() string            { return proto.CompactTextString(m) }
func (*CampsiteDetail) ProtoMessage()               {}
func (*CampsiteDetail) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{15} }

func (m *CampsiteDetail) GetResurgenceList() []*ResurgenceInfo {
	if m != nil {
		return m.ResurgenceList
	}
	return nil
}

// 占领类据点
type StrongholdDetail struct {
	NpcIsLife        *bool   `protobuf:"varint,1,req,name=NpcIsLife" json:"NpcIsLife,omitempty"`
	HP               *int32  `protobuf:"varint,2,req,name=HP" json:"HP,omitempty"`
	MineNum          *int32  `protobuf:"varint,3,req,name=MineNum" json:"MineNum,omitempty"`
	OtherNum         *int32  `protobuf:"varint,4,req,name=OtherNum" json:"OtherNum,omitempty"`
	NPCHPs           []int32 `protobuf:"varint,5,rep,name=NPCHPs" json:"NPCHPs,omitempty"`
	NPCAngers        []int32 `protobuf:"varint,6,rep,name=NPCAngers" json:"NPCAngers,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StrongholdDetail) Reset()                    { *m = StrongholdDetail{} }
func (m *StrongholdDetail) String() string            { return proto.CompactTextString(m) }
func (*StrongholdDetail) ProtoMessage()               {}
func (*StrongholdDetail) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{16} }

func (m *StrongholdDetail) GetNpcIsLife() bool {
	if m != nil && m.NpcIsLife != nil {
		return *m.NpcIsLife
	}
	return false
}

func (m *StrongholdDetail) GetHP() int32 {
	if m != nil && m.HP != nil {
		return *m.HP
	}
	return 0
}

func (m *StrongholdDetail) GetMineNum() int32 {
	if m != nil && m.MineNum != nil {
		return *m.MineNum
	}
	return 0
}

func (m *StrongholdDetail) GetOtherNum() int32 {
	if m != nil && m.OtherNum != nil {
		return *m.OtherNum
	}
	return 0
}

func (m *StrongholdDetail) GetNPCHPs() []int32 {
	if m != nil {
		return m.NPCHPs
	}
	return nil
}

func (m *StrongholdDetail) GetNPCAngers() []int32 {
	if m != nil {
		return m.NPCAngers
	}
	return nil
}

// 查看据点详情回调
type NationWar_StrongholdDetailResponse struct {
	Code             *int32             `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	OwnWarNum        *int32             `protobuf:"varint,2,req,name=OwnWarNum" json:"OwnWarNum,omitempty"`
	GridInfo         *NationWarGridInfo `protobuf:"bytes,3,req,name=GridInfo" json:"GridInfo,omitempty"`
	CampsiteInfo     *CampsiteDetail    `protobuf:"bytes,4,opt,name=CampsiteInfo" json:"CampsiteInfo,omitempty"`
	StrongholdInfo   *StrongholdDetail  `protobuf:"bytes,5,opt,name=StrongholdInfo" json:"StrongholdInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *NationWar_StrongholdDetailResponse) Reset()         { *m = NationWar_StrongholdDetailResponse{} }
func (m *NationWar_StrongholdDetailResponse) String() string { return proto.CompactTextString(m) }
func (*NationWar_StrongholdDetailResponse) ProtoMessage()    {}
func (*NationWar_StrongholdDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor60, []int{17}
}

func (m *NationWar_StrongholdDetailResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_StrongholdDetailResponse) GetOwnWarNum() int32 {
	if m != nil && m.OwnWarNum != nil {
		return *m.OwnWarNum
	}
	return 0
}

func (m *NationWar_StrongholdDetailResponse) GetGridInfo() *NationWarGridInfo {
	if m != nil {
		return m.GridInfo
	}
	return nil
}

func (m *NationWar_StrongholdDetailResponse) GetCampsiteInfo() *CampsiteDetail {
	if m != nil {
		return m.CampsiteInfo
	}
	return nil
}

func (m *NationWar_StrongholdDetailResponse) GetStrongholdInfo() *StrongholdDetail {
	if m != nil {
		return m.StrongholdInfo
	}
	return nil
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 据点相关请求
// 请求前往据点(通用)
type NationWar_MoveToRequest struct {
	WarNum           *int32 `protobuf:"varint,1,req,name=WarNum" json:"WarNum,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=Y" json:"Y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_MoveToRequest) Reset()                    { *m = NationWar_MoveToRequest{} }
func (m *NationWar_MoveToRequest) String() string            { return proto.CompactTextString(m) }
func (*NationWar_MoveToRequest) ProtoMessage()               {}
func (*NationWar_MoveToRequest) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{18} }

func (m *NationWar_MoveToRequest) GetWarNum() int32 {
	if m != nil && m.WarNum != nil {
		return *m.WarNum
	}
	return 0
}

func (m *NationWar_MoveToRequest) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NationWar_MoveToRequest) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

// 请求前往据点返回(通用)
type NationWar_MoveToResponse struct {
	Code             *int32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	PlayerObjID      *string `protobuf:"bytes,2,req,name=PlayerObjID" json:"PlayerObjID,omitempty"`
	PlayerFrame      *string `protobuf:"bytes,3,req,name=PlayerFrame" json:"PlayerFrame,omitempty"`
	PlayerIcon       *string `protobuf:"bytes,4,req,name=PlayerIcon" json:"PlayerIcon,omitempty"`
	Xs               []int32 `protobuf:"varint,5,rep,name=Xs" json:"Xs,omitempty"`
	Ys               []int32 `protobuf:"varint,6,rep,name=Ys" json:"Ys,omitempty"`
	StartIndex       *int32  `protobuf:"varint,7,req,name=StartIndex" json:"StartIndex,omitempty"`
	EndIndex         *int32  `protobuf:"varint,8,req,name=EndIndex" json:"EndIndex,omitempty"`
	EndTm            *int64  `protobuf:"varint,9,req,name=EndTm" json:"EndTm,omitempty"`
	MaxMoveTm        *int32  `protobuf:"varint,10,req,name=MaxMoveTm" json:"MaxMoveTm,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NationWar_MoveToResponse) Reset()                    { *m = NationWar_MoveToResponse{} }
func (m *NationWar_MoveToResponse) String() string            { return proto.CompactTextString(m) }
func (*NationWar_MoveToResponse) ProtoMessage()               {}
func (*NationWar_MoveToResponse) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{19} }

func (m *NationWar_MoveToResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_MoveToResponse) GetPlayerObjID() string {
	if m != nil && m.PlayerObjID != nil {
		return *m.PlayerObjID
	}
	return ""
}

func (m *NationWar_MoveToResponse) GetPlayerFrame() string {
	if m != nil && m.PlayerFrame != nil {
		return *m.PlayerFrame
	}
	return ""
}

func (m *NationWar_MoveToResponse) GetPlayerIcon() string {
	if m != nil && m.PlayerIcon != nil {
		return *m.PlayerIcon
	}
	return ""
}

func (m *NationWar_MoveToResponse) GetXs() []int32 {
	if m != nil {
		return m.Xs
	}
	return nil
}

func (m *NationWar_MoveToResponse) GetYs() []int32 {
	if m != nil {
		return m.Ys
	}
	return nil
}

func (m *NationWar_MoveToResponse) GetStartIndex() int32 {
	if m != nil && m.StartIndex != nil {
		return *m.StartIndex
	}
	return 0
}

func (m *NationWar_MoveToResponse) GetEndIndex() int32 {
	if m != nil && m.EndIndex != nil {
		return *m.EndIndex
	}
	return 0
}

func (m *NationWar_MoveToResponse) GetEndTm() int64 {
	if m != nil && m.EndTm != nil {
		return *m.EndTm
	}
	return 0
}

func (m *NationWar_MoveToResponse) GetMaxMoveTm() int32 {
	if m != nil && m.MaxMoveTm != nil {
		return *m.MaxMoveTm
	}
	return 0
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 请求回营复活(主动)
type NationWar_ResurgenceRequest struct {
	WarNum           *int32 `protobuf:"varint,1,req,name=WarNum" json:"WarNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_ResurgenceRequest) Reset()                    { *m = NationWar_ResurgenceRequest{} }
func (m *NationWar_ResurgenceRequest) String() string            { return proto.CompactTextString(m) }
func (*NationWar_ResurgenceRequest) ProtoMessage()               {}
func (*NationWar_ResurgenceRequest) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{20} }

func (m *NationWar_ResurgenceRequest) GetWarNum() int32 {
	if m != nil && m.WarNum != nil {
		return *m.WarNum
	}
	return 0
}

// 请求回营复活返回
type NationWar_ResurgenceResponse struct {
	Code             *int32             `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	PlayerObjID      *string            `protobuf:"bytes,2,req,name=PlayerObjID" json:"PlayerObjID,omitempty"`
	GridInfo         *NationWarGridInfo `protobuf:"bytes,3,req,name=GridInfo" json:"GridInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *NationWar_ResurgenceResponse) Reset()                    { *m = NationWar_ResurgenceResponse{} }
func (m *NationWar_ResurgenceResponse) String() string            { return proto.CompactTextString(m) }
func (*NationWar_ResurgenceResponse) ProtoMessage()               {}
func (*NationWar_ResurgenceResponse) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{21} }

func (m *NationWar_ResurgenceResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_ResurgenceResponse) GetPlayerObjID() string {
	if m != nil && m.PlayerObjID != nil {
		return *m.PlayerObjID
	}
	return ""
}

func (m *NationWar_ResurgenceResponse) GetGridInfo() *NationWarGridInfo {
	if m != nil {
		return m.GridInfo
	}
	return nil
}

// ////////////////////////////////////////////////////////////////////////////////////////
// 据点召集请求(通用)
type NationWar_CallRequest struct {
	WarNum           *int32 `protobuf:"varint,1,req,name=WarNum" json:"WarNum,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=Y" json:"Y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_CallRequest) Reset()                    { *m = NationWar_CallRequest{} }
func (m *NationWar_CallRequest) String() string            { return proto.CompactTextString(m) }
func (*NationWar_CallRequest) ProtoMessage()               {}
func (*NationWar_CallRequest) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{22} }

func (m *NationWar_CallRequest) GetWarNum() int32 {
	if m != nil && m.WarNum != nil {
		return *m.WarNum
	}
	return 0
}

func (m *NationWar_CallRequest) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NationWar_CallRequest) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

// 据点召集返回
type NationWar_CallResponse struct {
	Code             *int32 `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=X" json:"X,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=Y" json:"Y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *NationWar_CallResponse) Reset()                    { *m = NationWar_CallResponse{} }
func (m *NationWar_CallResponse) String() string            { return proto.CompactTextString(m) }
func (*NationWar_CallResponse) ProtoMessage()               {}
func (*NationWar_CallResponse) Descriptor() ([]byte, []int) { return fileDescriptor60, []int{23} }

func (m *NationWar_CallResponse) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *NationWar_CallResponse) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *NationWar_CallResponse) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerInfo)(nil), "msg.ServerInfo")
	proto.RegisterType((*NationWar_LoginSyncInfo)(nil), "msg.NationWar_LoginSyncInfo")
	proto.RegisterType((*NationWar_RegisterRequest)(nil), "msg.NationWar_RegisterRequest")
	proto.RegisterType((*NationWar_RegisterResponse)(nil), "msg.NationWar_RegisterResponse")
	proto.RegisterType((*NationWar_RegisterRankOpenRequest)(nil), "msg.NationWar_RegisterRankOpenRequest")
	proto.RegisterType((*NationWarRegisterGuild)(nil), "msg.NationWarRegisterGuild")
	proto.RegisterType((*NationWar_RegisterRankOpenResponse)(nil), "msg.NationWar_RegisterRankOpenResponse")
	proto.RegisterType((*NationWar_OpenWarMapRequest)(nil), "msg.NationWar_OpenWarMapRequest")
	proto.RegisterType((*NationWarMapInfo)(nil), "msg.NationWarMapInfo")
	proto.RegisterType((*NationWarGridInfo)(nil), "msg.NationWarGridInfo")
	proto.RegisterType((*NationWar_OpenWarMapResponse)(nil), "msg.NationWar_OpenWarMapResponse")
	proto.RegisterType((*NationWar_PlayerWarInfoRequest)(nil), "msg.NationWar_PlayerWarInfoRequest")
	proto.RegisterType((*NationWar_PlayerWarInfoResponse)(nil), "msg.NationWar_PlayerWarInfoResponse")
	proto.RegisterType((*NationWar_StrongholdDetailRequest)(nil), "msg.NationWar_StrongholdDetailRequest")
	proto.RegisterType((*ResurgenceInfo)(nil), "msg.ResurgenceInfo")
	proto.RegisterType((*CampsiteDetail)(nil), "msg.CampsiteDetail")
	proto.RegisterType((*StrongholdDetail)(nil), "msg.StrongholdDetail")
	proto.RegisterType((*NationWar_StrongholdDetailResponse)(nil), "msg.NationWar_StrongholdDetailResponse")
	proto.RegisterType((*NationWar_MoveToRequest)(nil), "msg.NationWar_MoveToRequest")
	proto.RegisterType((*NationWar_MoveToResponse)(nil), "msg.NationWar_MoveToResponse")
	proto.RegisterType((*NationWar_ResurgenceRequest)(nil), "msg.NationWar_ResurgenceRequest")
	proto.RegisterType((*NationWar_ResurgenceResponse)(nil), "msg.NationWar_ResurgenceResponse")
	proto.RegisterType((*NationWar_CallRequest)(nil), "msg.NationWar_CallRequest")
	proto.RegisterType((*NationWar_CallResponse)(nil), "msg.NationWar_CallResponse")
	proto.RegisterEnum("msg.NationalWarErrCode", NationalWarErrCode_name, NationalWarErrCode_value)
}

var fileDescriptor60 = []byte{
	// 1079 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0x45, 0x49, 0x96, 0x46, 0xb2, 0xcc, 0x30, 0x70, 0xc2, 0xc6, 0x45, 0xeb, 0x32, 0x28,
	0xe0, 0xa6, 0x88, 0x51, 0xe4, 0xdc, 0xa2, 0x08, 0x9c, 0x1f, 0xa9, 0x95, 0x29, 0xc1, 0x72, 0xd1,
	0xa4, 0x97, 0x82, 0x96, 0xd6, 0x32, 0x6b, 0x71, 0x57, 0x25, 0x29, 0xdb, 0x79, 0x9b, 0x02, 0xed,
	0xb1, 0xcf, 0xd0, 0x63, 0x81, 0xbe, 0x55, 0x66, 0x67, 0x77, 0x29, 0xca, 0xa1, 0x02, 0xf9, 0x24,
	0xf1, 0xe3, 0xcc, 0xec, 0xcc, 0x37, 0xdf, 0xcc, 0x12, 0x76, 0x79, 0x98, 0x45, 0x82, 0x87, 0xb3,
	0xeb, 0x30, 0xf9, 0x2d, 0x4e, 0xa7, 0x87, 0xf3, 0x44, 0x64, 0xc2, 0xb5, 0xf1, 0xaf, 0xff, 0x0c,
	0x60, 0xc4, 0x92, 0x2b, 0x96, 0xf4, 0xf8, 0xb9, 0x70, 0x1d, 0x68, 0xe8, 0xa7, 0x17, 0x9e, 0xb5,
	0x5f, 0x39, 0x68, 0xba, 0xae, 0x79, 0x1f, 0x84, 0x31, 0xf3, 0x2a, 0x12, 0xf3, 0xff, 0xa9, 0xc0,
	0xc3, 0x80, 0x42, 0xfe, 0x82, 0x01, 0xfb, 0x62, 0x1a, 0xf1, 0xd1, 0x3b, 0x3e, 0xa6, 0x08, 0x1d,
	0xa8, 0xff, 0x2a, 0x38, 0xd3, 0xfe, 0x35, 0x77, 0x07, 0xb6, 0xe4, 0x73, 0xb0, 0x88, 0xc9, 0xb9,
	0x26, 0x8f, 0x38, 0x59, 0xf0, 0x51, 0x16, 0x66, 0xcc, 0xb3, 0x09, 0xd9, 0x85, 0xed, 0x6e, 0x98,
	0x9e, 0xb0, 0x69, 0x94, 0x66, 0x2c, 0x61, 0x13, 0xaf, 0x86, 0x70, 0xc3, 0x7d, 0x08, 0x3b, 0x06,
	0x43, 0xeb, 0x24, 0x3b, 0x8d, 0xbd, 0x3a, 0xbe, 0xb0, 0xa5, 0xbd, 0x79, 0xf1, 0x92, 0x4f, 0x10,
	0xde, 0x22, 0x18, 0x33, 0xc5, 0x74, 0x8c, 0x69, 0x83, 0x30, 0x3c, 0x0c, 0x31, 0x65, 0xd5, 0x24,
	0xe4, 0xb1, 0xa9, 0xa7, 0x8f, 0x01, 0x3c, 0xd8, 0xb7, 0x0f, 0x5a, 0xcf, 0x76, 0x0e, 0x25, 0x29,
	0x05, 0x1a, 0x30, 0xd4, 0xeb, 0x45, 0x34, 0x9b, 0x0c, 0xce, 0x7e, 0xc7, 0x42, 0x5a, 0xfb, 0x96,
	0x22, 0x82, 0xb0, 0x3e, 0xbb, 0x62, 0x33, 0xaf, 0x8d, 0x18, 0xd5, 0x42, 0xd8, 0x8f, 0xe2, 0xcc,
	0xdb, 0x26, 0x04, 0xad, 0x8e, 0x23, 0xce, 0xf0, 0x50, 0x59, 0x71, 0x47, 0x62, 0xfe, 0x1e, 0x7c,
	0xba, 0x64, 0xcb, 0x64, 0x7e, 0xc2, 0xfe, 0x58, 0xb0, 0x34, 0xf3, 0x7f, 0x86, 0x47, 0x65, 0x2f,
	0xd3, 0xb9, 0xe0, 0x29, 0x73, 0xdb, 0x50, 0x3d, 0x12, 0x13, 0xa6, 0xb9, 0x5c, 0x0d, 0x5e, 0x29,
	0x27, 0x4f, 0x72, 0xda, 0xf0, 0x1f, 0xc3, 0x97, 0x25, 0x61, 0x43, 0x7e, 0x39, 0x98, 0x33, 0x6e,
	0xce, 0xfe, 0xd3, 0x82, 0x07, 0xb9, 0x95, 0x31, 0xa2, 0x82, 0xca, 0x85, 0x50, 0xe0, 0x84, 0x84,
	0xe0, 0xde, 0x83, 0x26, 0x61, 0xa4, 0x0d, 0x7b, 0xc5, 0x6c, 0x28, 0x22, 0x9e, 0x79, 0x55, 0x93,
	0xb7, 0xc6, 0xae, 0x59, 0x42, 0xdd, 0x5d, 0x62, 0xaf, 0x12, 0xe9, 0x5b, 0x27, 0xcc, 0x84, 0xeb,
	0x8d, 0x05, 0xa7, 0xa6, 0xd6, 0xfc, 0x2b, 0xf0, 0x3f, 0x56, 0xc7, 0xc6, 0x34, 0x1d, 0x9a, 0xd0,
	0xd8, 0x5e, 0xcc, 0x54, 0x76, 0x7d, 0x8f, 0xba, 0x5e, 0x5e, 0xbf, 0xff, 0x14, 0xf6, 0x96, 0xe7,
	0xca, 0xb3, 0xf0, 0xf7, 0x38, 0x9c, 0x6b, 0xe6, 0xa4, 0xca, 0x75, 0x78, 0x3a, 0x12, 0xa7, 0xc8,
	0xc9, 0xcd, 0xd1, 0x8c, 0x44, 0x24, 0x93, 0x0a, 0xe3, 0xb9, 0x4e, 0x4a, 0x29, 0x51, 0xb1, 0x42,
	0x29, 0xf9, 0xe7, 0x70, 0x2f, 0xf7, 0x79, 0x9d, 0x44, 0x94, 0x9a, 0xdb, 0x04, 0xeb, 0x8d, 0xf6,
	0xc0, 0xbf, 0x6f, 0x75, 0xf6, 0x26, 0x94, 0x4d, 0x1a, 0x03, 0xa8, 0x74, 0x87, 0x48, 0xad, 0xa5,
	0x28, 0x3b, 0x61, 0xe7, 0x09, 0x4b, 0x2f, 0x50, 0xe1, 0x35, 0x84, 0x6c, 0x99, 0x5b, 0x2f, 0xed,
	0x8b, 0xf1, 0x25, 0xb2, 0x6a, 0xa1, 0x14, 0xfe, 0xb5, 0xe0, 0xb3, 0xf2, 0x5a, 0x4a, 0xd9, 0x93,
	0xf3, 0xc9, 0xe2, 0x30, 0xe2, 0xa7, 0x8a, 0x3b, 0xdb, 0x7d, 0x02, 0x2d, 0xcd, 0xa7, 0x66, 0xaf,
	0x82, 0xec, 0xed, 0xae, 0xb2, 0x67, 0x8a, 0xfe, 0x06, 0xda, 0x83, 0xec, 0x82, 0x25, 0xc6, 0xb8,
	0xfa, 0x31, 0xe3, 0xaf, 0xa0, 0x26, 0x0b, 0x4f, 0x31, 0x71, 0xd9, 0x90, 0x07, 0xab, 0x56, 0x86,
	0x13, 0xff, 0x5b, 0xf8, 0x7c, 0x99, 0xff, 0x70, 0x16, 0xbe, 0xcb, 0xc3, 0xaf, 0x6b, 0xc7, 0xdf,
	0x16, 0x7c, 0xb1, 0xd6, 0xa5, 0xb4, 0x6a, 0xe2, 0xbd, 0xb2, 0xe4, 0x5d, 0x6d, 0xa6, 0xfb, 0xd0,
	0x7a, 0x3e, 0x96, 0x61, 0x8a, 0x6a, 0xce, 0xc1, 0xe0, 0x26, 0x23, 0xd2, 0x25, 0x47, 0xd8, 0x87,
	0x9f, 0xa2, 0xd9, 0xec, 0x48, 0x2c, 0xd0, 0x2e, 0x57, 0xb3, 0x82, 0xe2, 0x33, 0xa1, 0xd4, 0xec,
	0x6e, 0x43, 0xad, 0x3b, 0x1c, 0x26, 0x8c, 0xb6, 0x53, 0xcd, 0xef, 0x15, 0x87, 0x74, 0x94, 0x25,
	0x82, 0x4f, 0x2f, 0xc4, 0x6c, 0xf2, 0x82, 0x65, 0x61, 0x34, 0x5b, 0x53, 0x5b, 0x79, 0xa6, 0xfe,
	0x5f, 0x16, 0x74, 0xb0, 0xb4, 0x45, 0x32, 0x65, 0x7c, 0xcc, 0xd6, 0xef, 0xf2, 0x0d, 0x47, 0x58,
	0x51, 0x46, 0x58, 0x95, 0x30, 0x2c, 0x5a, 0x61, 0xc5, 0x19, 0x2e, 0x80, 0x51, 0x5e, 0xf6, 0x23,
	0x70, 0x15, 0xb8, 0x4c, 0xc7, 0xac, 0x68, 0xff, 0x7b, 0xe8, 0x48, 0x1d, 0xa7, 0x51, 0xc6, 0x54,
	0x91, 0xa8, 0x97, 0x42, 0xda, 0xb4, 0x92, 0x2d, 0xd2, 0xc2, 0x7d, 0xd2, 0xc2, 0x6a, 0x45, 0xfe,
	0x35, 0x38, 0xb7, 0x59, 0x92, 0xf9, 0x07, 0xf3, 0x31, 0x0a, 0x3e, 0x3a, 0x57, 0xbd, 0x6c, 0xe8,
	0xf9, 0xa8, 0x98, 0xeb, 0x47, 0x6a, 0x57, 0xd2, 0x67, 0x1b, 0x79, 0x93, 0x40, 0x25, 0xa2, 0xfa,
	0x89, 0x04, 0x07, 0xc3, 0xa3, 0xee, 0x50, 0xc9, 0x90, 0xfa, 0x86, 0xcf, 0xcf, 0xf9, 0x94, 0x25,
	0x29, 0xd6, 0x84, 0x90, 0xff, 0xbf, 0x55, 0x5c, 0x43, 0x1f, 0x76, 0xaa, 0x54, 0x52, 0x18, 0x67,
	0x70, 0xcd, 0x57, 0xb6, 0xd0, 0x01, 0xde, 0x17, 0x5a, 0xd5, 0x7a, 0x8c, 0xd6, 0x68, 0xde, 0xfd,
	0x1a, 0xda, 0x86, 0x29, 0x3d, 0x47, 0x56, 0xce, 0xca, 0x2d, 0x0a, 0x9f, 0x42, 0x67, 0x99, 0x11,
	0x19, 0xd7, 0xc8, 0x58, 0x0d, 0xdd, 0xed, 0x64, 0xfd, 0x1f, 0x8a, 0x77, 0xf7, 0xb1, 0xb8, 0x62,
	0xa7, 0xe2, 0x6e, 0x52, 0xfb, 0xcf, 0x02, 0xef, 0xc3, 0x08, 0xa5, 0x14, 0xe4, 0x02, 0x29, 0x2a,
	0x2e, 0x07, 0xd5, 0xea, 0xbf, 0xa5, 0x39, 0xda, 0xfd, 0x4a, 0x73, 0xd8, 0xc7, 0x37, 0xa6, 0x29,
	0xf8, 0xff, 0xad, 0xee, 0x06, 0x7d, 0x92, 0xc8, 0x5b, 0xbe, 0xc7, 0x27, 0xec, 0x46, 0x4f, 0x16,
	0xb6, 0x15, 0x6f, 0x79, 0x85, 0x34, 0xcc, 0xac, 0x15, 0xef, 0x7d, 0xec, 0xc6, 0x71, 0x78, 0x43,
	0xd9, 0xc6, 0x78, 0xed, 0xcb, 0x42, 0x56, 0x76, 0xfc, 0x52, 0x6a, 0xeb, 0x96, 0xca, 0x65, 0x71,
	0x8d, 0x16, 0xcd, 0x37, 0x2f, 0x7d, 0xe3, 0xfe, 0xe3, 0xa4, 0xec, 0x2e, 0x0f, 0x3b, 0x0a, 0x67,
	0x77, 0x5c, 0x07, 0xdf, 0x15, 0x2e, 0x76, 0xed, 0xbe, 0xf9, 0xda, 0x7b, 0x82, 0x72, 0x77, 0x03,
	0xfd, 0xc9, 0x28, 0x3f, 0x9f, 0x92, 0x44, 0xba, 0xb8, 0x2d, 0xd8, 0x1a, 0x2d, 0xc6, 0x63, 0x96,
	0xa6, 0xce, 0x27, 0x6e, 0x03, 0xaa, 0xaf, 0x50, 0x4e, 0x8e, 0x85, 0xdd, 0xa8, 0x07, 0x42, 0x5e,
	0x2b, 0x4e, 0x45, 0x9a, 0x04, 0x82, 0xf6, 0x89, 0x63, 0xe3, 0x51, 0x0d, 0xfc, 0x30, 0xea, 0x47,
	0x71, 0x94, 0x39, 0x55, 0x4c, 0x1c, 0xe8, 0xd3, 0x49, 0x3d, 0xcb, 0xf1, 0x58, 0xfd, 0x70, 0x71,
	0xea, 0x12, 0x1a, 0x2c, 0x32, 0x03, 0x9d, 0xc6, 0xce, 0x96, 0xf4, 0x92, 0xe5, 0x8a, 0x97, 0x37,
	0x88, 0x39, 0x0d, 0xec, 0x73, 0x3b, 0x10, 0x05, 0xa7, 0xa6, 0x3c, 0x05, 0x9d, 0xd0, 0x08, 0xed,
	0x01, 0xe7, 0xbd, 0xd5, 0x45, 0xad, 0x1b, 0x87, 0xd6, 0xfb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69,
	0x52, 0x91, 0x6b, 0xfc, 0x0a, 0x00, 0x00,
}
